# Generated by Django 4.0.5 on 2022-06-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadejornada',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='jornada.jornada'),
        ),
    ]
