# Generated by Django 4.0.5 on 2022-06-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('wp', 'Whatsapp'), ('nt', 'Notícia'), ('wb', 'Website')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Fato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('fake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatos', to='fato_ou_fake.fakenews')),
            ],
        ),
    ]
