# Generated by Django 4.0.5 on 2022-06-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BaseInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ART', 'Artigo'), ('WIK', 'Wikipédia da saúde'), ('NOT', 'Notícias'), ('PES', 'Pesquisa')], max_length=4)),
                ('data_publicacao', models.DateTimeField()),
                ('acessos', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('area', models.ManyToManyField(related_name='conteudos', to='informacoes.area')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WikipediaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('informacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikipedia', to='informacoes.baseinformacao')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('informacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='informacoes.baseinformacao')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('informacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='informacoes.baseinformacao')),
            ],
        ),
        migrations.AddField(
            model_name='baseinformacao',
            name='palavras_chave',
            field=models.ManyToManyField(related_name='conteudos', to='informacoes.tag'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('informacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='informacoes.baseinformacao')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('capital_executado', models.FloatField(blank=True, null=True)),
                ('programa', models.CharField(max_length=255)),
                ('informacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigo', to='informacoes.baseinformacao')),
            ],
        ),
    ]
