# Generated by Django 4.0.5 on 2022-06-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='informacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artigo', to='informacoes.baseinformacao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='informacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='informacoes.baseinformacao'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='informacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='informacoes.baseinformacao'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='informacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='informacoes.baseinformacao'),
        ),
        migrations.AlterField(
            model_name='wikipediasaude',
            name='informacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wikipedia', to='informacoes.baseinformacao'),
        ),
    ]
