# Generated by Django 4.0.5 on 2022-06-17 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0003_orgao_relatorio_estado_alter_baseinformacao_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('CD', 'Contratação Direta'), ('FD', 'Fomento Descentralizado - PPSUS'), ('FN', 'Fomento Nacional')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='aplicabilidade_sus',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='coordenador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='instituicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='metodologia',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='objetivo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='patente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='producoes_cientificas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informacoes.baseinformacao'),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='valor_investido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Editais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editais', to='informacoes.baseinformacao')),
            ],
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informacoes.edital'),
        ),
    ]
