# Generated by Django 4.0.5 on 2022-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0004_edital_pesquisa_aplicabilidade_sus_pesquisa_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CD', 'Contratação Direta'), ('FD', 'Fomento Descentralizado - PPSUS'), ('FN', 'Fomento Nacional')], max_length=2, null=True),
        ),
    ]
