# Generated by Django 4.0.5 on 2022-06-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0006_pesquisa_regiao_alter_pesquisa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='status',
            field=models.CharField(blank=True, choices=[('AN', 'Em andamento'), ('FN', 'Finalizado')], max_length=3, null=True),
        ),
    ]
