# Generated by Django 4.0.5 on 2022-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0007_pesquisa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='aplicabilidade_sus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='metodologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
