# Generated by Django 4.0.5 on 2022-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0008_alter_pesquisa_aplicabilidade_sus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='arquivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
